[package]
name = "servertui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
crossterm = "0.29.0"
local-ip-address = "0.6.5"
ratatui = "0.29.0"
regex = "1.12.2"
sysinfo = "0.37.2"
